project_id = "vsliunuaifngxannjmxd"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322

[functions.generate-lead-magnet]
verify_jwt = true