// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vsliunuaifngxannjmxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzbGl1bnVhaWZuZ3hhbm5qbXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDg2NDgsImV4cCI6MjA3MjcyNDY0OH0.RWLghvrpEpc5ppkvleKj_P2sSpRam6jnXNPtjz-3p4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});